### ISSUE TITLE
Queue Issues

### ISSUE THREAD

**Issue by scratties** [ricozyx/Discord-TenshiBot#14]
Hello, i dowloanded this repos. And i write token, ownerıd and i started bot. But when i playing a music "Stopped playing music as the queue is empty." sending this embed. Bot joins the voice channel and immediately exits and gives this warning. 
![image](https://user-images.githubusercontent.com/73654370/112624346-94c53200-8e3e-11eb-9a0b-7f44d16e8339.png)

**Comment by Charcadet** [comment]
Make sure discordjs/opus and all the other nodejs packages are up-to-date. Also make sure you have ffmpeg installed. 

If there is any error in the bots console please share this.

**Comment by scratties** [comment]
There is no error message or a message on the console. I checked all the nodejs modules, all up to date but still getting the same error. I have no idea why. Thanks anyway. 
![image](https://user-images.githubusercontent.com/73654370/112717131-addfe880-8efb-11eb-8702-3ef7f4f049f4.png)

**Comment by Charcadet** [comment]
Did you install FFMPEG? (It’s not a nodejs module)


________________________________

**Comment by scratties** [comment]
Thank you very much, dude. I installed Ffmpeg and it worked. Thanks for this job. I gave stars.

**Comment by Charcadet** [comment]
Thanks for the nice words, appreciate it. Glad you got it all running now.
